### ISSUE TITLE
Request to add command-lines to miRNASeq workflow

### ISSUE THREAD

**Issue by bhidek** [Zymo-Research/service-pipeline-documentation#19]
Hello,

This is Ketaki Bhide from Purdue Bioinformatics Core. We are working with Zymo for one of our collaborator's MultiOmics project.

We are trying to repeat analysis for couple of samples as a test using workflow from 
https://github.com/Zymo-Research/service-pipeline-documentation/blob/master/docs/how_to_use_miRNAseq_report.md 

We are having some discrepancy in expressed miRNA numbers  (from results files Zymo sent) while trying to repeat the analysis.

Could you please add the command-lines for all tools used in the workflow. It would be really helpful.

Thank you
Ketaki Bhide
Bioinformatics Analyst

**Comment by zxl124** [comment]
Hi Ketaki,

To completely replicate our results, it would require source code of the entire pipeline. We are unable to release that to you unless authorized by our Service Department. We made clear in our [pipeline documentation](https://github.com/Zymo-Research/service-pipeline-documentation/blob/master/docs/how_to_use_miRNAseq_report.md#bioinformatics-pipeline-overview) that our pipeline is adapted from [nf-core smrnaseq pipeline v1.0.0](https://github.com/nf-core/smrnaseq/releases/tag/1.0.0). You can find the command lines for each step there. Notable changes we made include the following:
1. If your library prep kit is Zymo's miRNAseq kit, we trim 1bp off 5' end of reads using Trim-Galore with the option `--clip_R1 1`. 
2. We changed the bowtie command aligning collapsed reads to hairpin miRNAs from `-k 50` to `-m 50`.
3. Instead of using raw reads as input for miRTrace, we use reads after trimming.
4. Make additional QC plots and differential expression analysis using `isomiRs`.
5. Updated versions of some software. You can find software versions we used at the end of each report.

If you have further questions of specific steps, please do not hesitate to contact us again. Thank you.

**Comment by bhidek** [comment]
Hello Zhenfeng Liu,

Thank you for your response. The list of notable changes and link to pipleine documentation is very helpful.

If I have additional questions, I will get back to you.

Regards
Ketaki
